### ISSUE TITLE
Timer start From Its Initial Value every time i click on Button or Any Event

### ISSUE THREAD

**Issue by appongit** [noelyoo/react-native-timer-countdown#10]
Please any one tell me how can i fix this

**Comment by noelyoo** [comment]
Hi, @appongit check this: https://github.com/noelyoo/react-native-timer-countdown/issues/7

**Comment by appongit** [comment]
I am new in react native so i dont know about this
render(){
        return(
            <StateChangingComponent renderTimerCountdown={()=><TimerCountdown/>}/>
        );
}
can you explain more

**Comment by noelyoo** [comment]
This it what is happening:
button click -> state changes -> react renders again -> timer restarting

How to not restart the timer component:
let's say we have 3 components: 
1) A component
2) B component
3) timer component

In B component, your button events are handled. 
In A component, there are no state changes and it just contains B component passing the timer component as props. 
```
// A.jsx
(...)
render(){
        return(
            <B TimerComonent={<TimerCountdown/>}/>
        );
}
```

In B component, you render the timer component like this:
```
render(){
        return(
                <View>
                    {this.props.TimerComonent}
                </View>
        );
}
```

I hope it helps.

**Comment by appongit** [comment]
Hi i did it but not working fine
here is my code
```
import React, { Component } from 'react';
import { Text, View, StyleSheet, Button } from 'react-native';
import { Constants } from 'expo';
import TimerCountdown from 'react-native-timer-countdown'
export default class A extends Component {
  state = {data:""}
  render() {
    return (
      <View style={styles.container}>
        <Button title="Click me" onPress={()=>{this.setState({data:3})}}></Button>
        <B timer={<Timer/>}/>
      </View>
    );
  }
}

class B extends Component {
  render(){
    return(<Text>{this.props.timer}</Text>)
  }
}

class Timer extends Component {
  render(){
    return(<TimerCountdown
            initialSecondsRemaining={60000}
            onTick={secondsRemaining => console.log('tick', secondsRemaining)}
            onTimeElapsed={() => console.log('complete')}
            allowFontScaling={true}
            style={{ fontSize: 20 }}
        />)
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  }
});
```

**Comment by noelyoo** [comment]
@appongit 
You just **edited your code**. What you did wrong was changing the state in A component. Now you changed the state change in B component, it should be working now.

**Comment by noelyoo** [comment]
This is the working example:
```
import React, { Component } from 'react';
import { StyleSheet, Button, View } from 'react-native';
import TimerCountdown from 'react-native-timer-countdown';

export default class A extends Component {
  render() {
    return (
      <View style={styles.container}>
        <B renderTimer={() => <Timer />} />
      </View>
    );
  }
}

class B extends Component {
  state = { isPressed: false }
  render() {
    return (
      <View styles={{ flex: 1 }}>
        {this.props.renderTimer()}
        <Button
          title={`${this.state.isPressed ? 'Button Pressed' : 'Button'}`}
          onPress={() => { this.setState({ isPressed: true }) }}
        />
      </View >
    )
  }
}

const Timer = () => (
  <TimerCountdown
    initialSecondsRemaining={60000}
    onTick={secondsRemaining => console.log('tick', secondsRemaining)}
    onTimeElapsed={() => console.log('complete')}
    allowFontScaling={true}
    style={{ fontSize: 20 }}
  />
);


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by noelyoo** [comment]
@appongit README updated:
https://github.com/noelyoo/react-native-timer-countdown/commit/187fc2373fe25755d7371b9d7b337d4ee0746c8d

**Comment by aliwaqassi** [comment]
I try your example here is result
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19648354/41277938-045826c4-6e42-11e8-84a0-992077bb197e.gif)

**Comment by aliwaqassi** [comment]
Please help i am waiting

**Comment by noelyoo** [comment]
@aliwaqassi My bad. I just updated the code.

**Comment by aliwaqassi** [comment]
yes i did it but not working still

**Comment by noelyoo** [comment]
@aliwaqassi I'm sorry but think you need to debug yourself for that. 
![oapii79cmu](https://user-images.githubusercontent.com/25740248/41324811-c031a294-6ef1-11e8-856f-76b10abf390c.gif)

**Comment by aliwaqassi** [comment]
yeah, my mistake was there `<B timer={<Timer/>}/>`
Thanks @noelyoo

**Comment by noelyoo** [comment]
@aliwaqassi Great, I made my explanation clearer thanks to you guys. 
If you satisfied, it would be nice to star this repo 👍
