### ISSUE TITLE
Time reset when click any button

### ISSUE THREAD

**Issue by aliwaqassi** [noelyoo/react-native-timer-countdown#11]
Thanks for share this repo that`s is so good,
Is there any solution for this, Thanks

**Comment by noelyoo** [comment]
@aliwaqassi Hi, Check this one: https://github.com/noelyoo/react-native-timer-countdown/issues/10

**Comment by noelyoo** [comment]
@aliwaqassi README updated:
https://github.com/noelyoo/react-native-timer-countdown/commit/187fc2373fe25755d7371b9d7b337d4ee0746c8d

**Comment by noelyoo** [comment]
@aliwaqassi README updated:
https://github.com/noelyoo/react-native-timer-countdown/commit/b36b8b7a56f3ede6ac0030134f0d4883bb3b6714
