### ISSUE TITLE
JSX props should not use arrow functions

### ISSUE THREAD

**Issue by abhichourasia** [noelyoo/react-native-timer-countdown#17]
So I am getting ES Lint warning "JSX props should not use arrow functions" for below code:
`onTick={secondsRemaining =>  this.myNewFunction(secondsRemaining)}`
` onTimeElapsed={() => this.myFunction()}`

Just wanted to know what can be done for this to get rid of warning?

**Comment by abhichourasia** [comment]
I created a separate component of it and resolved the issue!
Thank you very much!

**Comment by noelyoo** [comment]
Kindly check this: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md
