### ISSUE TITLE
Expose this library's default text formatter for re-use & consistency

### ISSUE THREAD

**Issue by toblerpwn** [noelyoo/react-native-timer-countdown#18]
**Is your feature request related to a problem? Please describe.**
While pausing the timer, or representing the time remaining elsewhere in a component, I would like to represent the time remaining in exactly the same format (e.g. `mm:ss`).

**Describe the solution you'd like**
I would love to see a `formatText()` method (static or instance) OR some kind of accessible prop that can format external text in the same format as this project (e.g. leading zeroes, as in `09:04` time remaining instead of `9:4`).

Note that this differs from the current `formatSecondsRemaining()` prop in that I would like to use _your_ formatter and not build my own / provide one to you.

**Describe alternatives you've considered**
Currently, in my code base, I am re-constructing the text formatting code. However, I cannot be sure that it matches this code base exactly (e.g. > 100 minutes? > 1 hour?) for a given # of seconds remaining!

This is my code fwiw, but it shouldn't be needed here--I think we should just expose the formatter as it is today:

```
export function timeStringFromMillis(millis: number) {
  const seconds = millis / 1000;
  const minutes = Math.floor(seconds / 60);
  const wholeSecondsRemaining = Math.floor(seconds % 60);
  const secondsString = (wholeSecondsRemaining > 9) ? wholeSecondsRemaining.toString() : `0${wholeSecondsRemaining}`;
  const minutesString = (minutes > 9) ? minutes.toString() : `0${minutes}`;
  return `${minutesString}:${secondsString}`;
}
```

**Comment by noelyoo** [comment]
@toblerpwn IMO, `formatSecondsRemaining` should be enough to solve the formatting issue.
and this lines might help you.
https://github.com/noelyoo/react-native-timer-countdown/blob/master/index.tsx#L97-L112

```
 private getFormattedTime = (milliseconds: number): string => {
    if (this.props.formatSecondsRemaining) {
      return this.props.formatSecondsRemaining(milliseconds);
    }
    const remainingSec = Math.round(milliseconds / 1000);

    const seconds: number = parseInt((remainingSec % 60).toString(), 10);
    const minutes: number = parseInt(((remainingSec / 60) % 60).toString(), 10);
    const hours: number = parseInt((remainingSec / 3600).toString(), 10);

    const s = seconds < 10 ? '0' + seconds : seconds;
    const m = minutes < 10 ? '0' + minutes : minutes;
    let h = hours < 10 ? '0' + hours : hours;
    h = h === '00' ? '' : h + ':';
    return h + m + ':' + s;
  };
```

**Comment by noelyoo** [comment]
I just updated README.md exposing the default `getFormattedTime` function as an example so that people can customize it as they want.

https://github.com/noelyoo/react-native-timer-countdown/commit/f81f9e36373c7c037b7597d85fb204d68f971700
