### ISSUE TITLE
onTick method returns NaN value

### ISSUE THREAD

**Issue by Ektasahusahu** [noelyoo/react-native-timer-countdown#19]
I am calling timer into flatList but onTick methods returns NaN value all the time

**Comment by noelyoo** [comment]
Hey, @Ektasahusahu 

The `onTick` only runs your custom code. In this module, onTick is an optional and the default value is undefined.

Check this out:
```
    if (this.props.onTick !== undefined) {
      this.props.onTick(millisecondsRemaining);
    }
```
https://github.com/noelyoo/react-native-timer-countdown/blob/master/index.tsx#L81-L83

Therefore, if `onTick` returns `NaN` value all the time, then possibly you are passing some function which returns `NaN` value all the time. 

I think it would be great if you could provide some reproducible sample code for your issue to help you out. Thanks.
